name: "Validate Terraform modules"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - feature/pr-actions # remove before PR

jobs:
  validate_modules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - infra/dns
    name: "Validate ${{ matrix.module }} module"
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Load secrets
        id: load-secrets
        uses: 1password/load-secrets-action@v4
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          TF_API_TOKEN: "op://Valheim/Terraform - GitHub Actions/credential"
      - uses: ./.github/actions/setup
        id: setup
        with:
          working-directory: '${{ matrix.module }}'
          tf-api-token: ${{ steps.load-secrets.outputs.TF_API_TOKEN }}